In [1]:
#read balanced data
import pandas as pd
df = pd.read_csv('(raw) Monthly_data.csv')

In [2]:
len(df)

153

In [3]:
#check null values
df.isnull().sum()
#print null rows
df[df.isnull().any(axis=1)]
df.dropna(inplace=True)


In [4]:
#use SVM
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


In [5]:
#split data into training and testing
X = df.drop(['CCt'], axis=1)
y = df['CCt']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)



In [6]:
#fit SVM model
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
y_pred = clf.predict(X_test)


In [9]:
#accuracy
import sklearn.metrics as metrics

print("Accuracy:",accuracy_score(y_test, y_pred))
#confusion matrix
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
#classification report
print("Classification Report:\n",classification_report(y_test, y_pred))
print("area under curve (auc): ", metrics.roc_auc_score(y_test, y_pred))


Accuracy: 0.9354838709677419
Confusion Matrix:
 [[29  0]
 [ 2  0]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.94      1.00      0.97        29
         1.0       0.00      0.00      0.00         2

    accuracy                           0.94        31
   macro avg       0.47      0.50      0.48        31
weighted avg       0.88      0.94      0.90        31

area under curve (auc):  0.5


c:\Users\User\anaconda3\envs\sklearn1.0\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
#use raw data
df_raw = pd.read_csv('(raw) Quarterly_data.csv')
#drop NaN values
df_raw = df_raw.dropna()
X_raw = df_raw.drop(['CCt'], axis=1)
y_raw = df_raw['CCt']

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(X_raw, y_raw, test_size=0.2, random_state=0)
#fit SVM model
clf_raw = svm.SVC(kernel='linear', C=1).fit(X_train_raw, y_train_raw)
y_pred_raw = clf_raw.predict(X_test_raw)
#accuracy
print("Accuracy:",accuracy_score(y_test_raw, y_pred_raw))
#confusion matrix
print("Confusion Matrix:\n",confusion_matrix(y_test_raw, y_pred_raw))
#classification report
print("Classification Report:\n",classification_report(y_test_raw, y_pred_raw))
print("area under curve (auc): ", metrics.roc_auc_score(y_test_raw, y_pred_raw))


Accuracy: 0.7
Confusion Matrix:
 [[7 0]
 [3 0]]
Classification Report:
               precision    recall  f1-score   support

         0.0       0.70      1.00      0.82         7
         1.0       0.00      0.00      0.00         3

    accuracy                           0.70        10
   macro avg       0.35      0.50      0.41        10
weighted avg       0.49      0.70      0.58        10

area under curve (auc):  0.5


c:\Users\User\anaconda3\envs\sklearn1.0\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
#print out all the test data
print("Test Data:\n",y_pred_raw)

Test Data:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
#print out all the test balance data
print("Test Data:\n",y_pred)

Test Data:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0.]
